version: "3.1"

#
# Hodl Trading Desk
#
services:
    db:
        image: postgres:15
        container_name: hodl-td-db.local
        restart: unless-stopped
        networks:
            - hodl-td-net-be
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./postgres/data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: hodl-td-pgadmin.local
        restart: unless-stopped
        networks:
            - hodl-td-net-be
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./pgadmin:/var/lib/pgadmin
        ports:
            - 8082:80

    hodl-td-api:
        #image: registry.gitlab.com/hodl.nl/hodltradingdesk/hodl-td-api:dev
        image: hodl-td-api:local
        container_name: hodl-td-api.local
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - hodl-td-net-fe
            - hodl-td-net-be
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - ./appsettings.json:/app/appsettings.json
        ports:
            - 8081:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development

    hodl-td-fe:
        image: registry.gitlab.com/hodl.nl/trading-desk-hodl-reactjs/hodl-td-fe:dev
        container_name: hodl-td-fe.local
        networks:
            - hodl-td-net-fe
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./config.json:/usr/share/nginx/html/config.json
        ports:
            - 8080:3000
        restart: unless-stopped

networks:
    hodl-td-net-fe:
        name: hodl-td-net-fe
        driver: bridge
    hodl-td-net-be:
        name: hodl-td-net-be
        driver: bridge
