// <auto-generated />
using System;
using Hodl.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hodl.Api.Migrations
{
    [DbContext(typeof(HodlDbContext))]
    [Migration("20220726142756_AddNavFields")]
    partial class AddNavFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.AppChangeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewRecord")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedRoleName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OldRecord")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChangeLog");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.AppConfig", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedRoleName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1a6e520-01f1-4fed-85e1-a2a358d7fb02"),
                            ConcurrencyStamp = "48e6d688-9a29-425a-8b05-d1dfef029ace",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("526198db-4e9f-4200-bbf9-82ecfe39330c"),
                            ConcurrencyStamp = "9aafaeb9-fb86-4a0e-84bf-4d6a867472a7",
                            Name = "Trader",
                            NormalizedName = "TRADER"
                        },
                        new
                        {
                            Id = new Guid("d12fa1e4-409f-42f6-900c-dbd8295ca1cf"),
                            ConcurrencyStamp = "a6694269-ae1e-44a8-b582-9bfb43f7f864",
                            Name = "LeadTrader",
                            NormalizedName = "LEADTRADER"
                        },
                        new
                        {
                            Id = new Guid("bc1bd304-deee-4ecb-b00e-420484984c83"),
                            ConcurrencyStamp = "9bb16b51-4f6c-4e99-bef7-b5d6476ff8af",
                            Name = "Sales",
                            NormalizedName = "SALES"
                        },
                        new
                        {
                            Id = new Guid("0aff7b76-053d-43d9-aa1b-308df84c32e1"),
                            ConcurrencyStamp = "5fd4ce7d-7a99-4144-927e-081abdb82a59",
                            Name = "HeadSales",
                            NormalizedName = "HEADSALES"
                        },
                        new
                        {
                            Id = new Guid("420d65a9-f385-4f19-9c25-b48eaa4ee2dd"),
                            ConcurrencyStamp = "3f31d2ae-b6a6-4c2f-8078-58281d4336ec",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Branch")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("City")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Country")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("BIC")
                        .IsUnique();

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<string>("HolderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("FundId");

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.BankBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyISOCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyISOCode");

                    b.HasIndex("BankAccountId", "CurrencyISOCode")
                        .IsUnique();

                    b.HasIndex("BankAccountId", "CurrencyISOCode", "TimeStamp");

                    b.ToTable("BankBalances");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.BlockchainNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChainID")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ExplorerUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RPCUrl")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("BlockchainNetworks");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Group", "Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.CryptoCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CryptoId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryId", "CryptoId");

                    b.HasIndex("CryptoId", "CategoryId")
                        .IsUnique();

                    b.ToTable("CryptoCategory");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.CryptoCurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<byte>("Decimals")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsFiat")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Name")
                        .IsUnique();

                    b.ToTable("CryptoCurrencies");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Currency", b =>
                {
                    b.Property<string>("ISOCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<byte>("Decimals")
                        .HasColumnType("smallint");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("ISOCode");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.CurrencyRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CyrrencyISOCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("USDRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CyrrencyISOCode", "TimeStamp");

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExchangeName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDefi")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.ExchangeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountKey")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex("ExchangeId", "AccountKey")
                        .IsUnique();

                    b.ToTable("ExchangeAccounts");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdministrationFee")
                        .HasColumnType("integer");

                    b.Property<int>("AdministrationFeeFrequency")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("FundOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("LayerStrategy")
                        .HasColumnType("text");

                    b.Property<int>("MaxVolume")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedFundName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PerformanceFee")
                        .HasColumnType("integer");

                    b.Property<Guid>("PrimaryCryptoCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportingCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("ShareValueHWM")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalShares")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FundOwnerId");

                    b.HasIndex("NormalizedFundName")
                        .IsUnique();

                    b.HasIndex("PrimaryCryptoCurrencyId");

                    b.HasIndex("ReportingCurrencyCode");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.FundCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<byte>("MaxPercentage")
                        .HasColumnType("smallint");

                    b.Property<byte>("MinPercentage")
                        .HasColumnType("smallint");

                    b.HasKey("CategoryId", "FundId");

                    b.HasIndex("FundId", "CategoryId")
                        .IsUnique();

                    b.ToTable("FundCategories");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.FundLayer", b =>
                {
                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<byte>("LayerIndex")
                        .HasColumnType("smallint");

                    b.Property<byte>("AimPercentage")
                        .HasColumnType("smallint");

                    b.Property<byte>("AlertRangeHigh")
                        .HasColumnType("smallint");

                    b.Property<byte>("AlertRangeLow")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("FundId", "LayerIndex");

                    b.HasIndex("FundId", "LayerIndex");

                    b.ToTable("FundLayers");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.FundOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Department")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("FundOwners");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingPeriod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<Guid?>("CryptoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyISOCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long?>("CurrencyRateId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EndBTCPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EndBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EndPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EndUSDPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<byte>("LayerIndex")
                        .HasColumnType("smallint");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PeriodClosedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousHoldingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StartBTCPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StartBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StartUSDPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId");

                    b.HasIndex("CurrencyISOCode");

                    b.HasIndex("CurrencyRateId");

                    b.HasIndex("ListingId");

                    b.HasIndex("PreviousHoldingId")
                        .IsUnique();

                    b.HasIndex("FundId", "BookingPeriod", "CurrencyISOCode");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Listing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BTCPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CirculatingSupply")
                        .HasColumnType("numeric");

                    b.Property<int>("CmcRank")
                        .HasColumnType("integer");

                    b.Property<Guid>("CryptoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxSupply")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentChange_1h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentChange_24h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentChange_7d")
                        .HasColumnType("numeric");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalSupply")
                        .HasColumnType("numeric");

                    b.Property<decimal>("USDPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Volume_24h")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId", "TimeStamp");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Nav", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingPeriod")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<long>("CurrencyRateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ShareGross")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ShareHWM")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ShareNAV")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalShares")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyRateId");

                    b.HasIndex("FundId", "DateTime");

                    b.ToTable("Navs");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ExchangeAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromCryptoId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToCryptoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId");

                    b.HasIndex("WalletAddress");

                    b.HasIndex("FromCryptoId", "State");

                    b.HasIndex("ToCryptoId", "State");

                    b.HasIndex("FromCryptoId", "Type", "DateTime");

                    b.HasIndex("ToCryptoId", "Type", "DateTime");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.OrderFunding", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OrderPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("numeric");

                    b.HasKey("OrderId", "FundId");

                    b.HasIndex("FundId");

                    b.HasIndex("OrderId", "FundId")
                        .IsUnique();

                    b.ToTable("OrderFundings");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Pair", b =>
                {
                    b.Property<string>("PairString")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<Guid>("FromCryptoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToCryptoId")
                        .HasColumnType("uuid");

                    b.HasKey("PairString");

                    b.HasIndex("ToCryptoId");

                    b.HasIndex("FromCryptoId", "ToCryptoId");

                    b.ToTable("Pairs");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingPeriod")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Executed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FeeCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FeeCurrencyId");

                    b.HasIndex("OrderId", "BookingPeriod");

                    b.HasIndex("OrderId", "DateTime");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingPeriod")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HoldingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OppositeTransferId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Shares")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransactionSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TransferAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TransferFee")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OppositeTransferId");

                    b.HasIndex("HoldingId", "BookingPeriod", "DateTime");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DescriptionMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityTitle")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<string>("OptionalData")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExchangeAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Address");

                    b.HasIndex("ExchangeAccountId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.WalletBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BlockchainNetworkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CryptoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainNetworkId");

                    b.HasIndex("CryptoId", "BlockchainNetworkId");

                    b.HasIndex("Address", "CryptoId", "BlockchainNetworkId")
                        .IsUnique();

                    b.ToTable("WalletBalances");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.AppChangeLog", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.BankAccount", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Fund", "Fund")
                        .WithMany("BankAccounts")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.BankBalance", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.BankAccount", "BankAccount")
                        .WithMany("Balances")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyISOCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.CryptoCategory", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Category", "Category")
                        .WithMany("CryptoCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "CryptoCurrency")
                        .WithMany()
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CryptoCurrency");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.CurrencyRate", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Currency", "Currency")
                        .WithMany("CurrencyRates")
                        .HasForeignKey("CyrrencyISOCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.ExchangeAccount", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Exchange", "Exchange")
                        .WithMany("ExchangeAccounts")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.ExchangeAccount", "ParentAccount")
                        .WithMany("ChildAccounts")
                        .HasForeignKey("ParentAccountId");

                    b.Navigation("Exchange");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Fund", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.FundOwner", "FundOwner")
                        .WithMany("Funds")
                        .HasForeignKey("FundOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "PrimaryCryptoCurrency")
                        .WithMany()
                        .HasForeignKey("PrimaryCryptoCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Currency", "ReportingCurrency")
                        .WithMany()
                        .HasForeignKey("ReportingCurrencyCode");

                    b.Navigation("FundOwner");

                    b.Navigation("PrimaryCryptoCurrency");

                    b.Navigation("ReportingCurrency");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.FundCategory", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Category", "Category")
                        .WithMany("FundCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Fund", "Fund")
                        .WithMany("FundCategories")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.FundLayer", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Fund", "Fund")
                        .WithMany("Layers")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Holding", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "CryptoCurrency")
                        .WithMany("Holdings")
                        .HasForeignKey("CryptoId");

                    b.HasOne("Hodl.Api.HodlDbDomain.Currency", "Currency")
                        .WithMany("Holdings")
                        .HasForeignKey("CurrencyISOCode");

                    b.HasOne("Hodl.Api.HodlDbDomain.CurrencyRate", "CurrencyRate")
                        .WithMany()
                        .HasForeignKey("CurrencyRateId");

                    b.HasOne("Hodl.Api.HodlDbDomain.Fund", "Fund")
                        .WithMany("Holdings")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId");

                    b.HasOne("Hodl.Api.HodlDbDomain.Holding", "PreviousHolding")
                        .WithOne("NextHolding")
                        .HasForeignKey("Hodl.Api.HodlDbDomain.Holding", "PreviousHoldingId");

                    b.Navigation("CryptoCurrency");

                    b.Navigation("Currency");

                    b.Navigation("CurrencyRate");

                    b.Navigation("Fund");

                    b.Navigation("Listing");

                    b.Navigation("PreviousHolding");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Listing", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "CryptoCurrency")
                        .WithMany("Listings")
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoCurrency");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Nav", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.CurrencyRate", "CurrencyRate")
                        .WithMany()
                        .HasForeignKey("CurrencyRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Fund", "Fund")
                        .WithMany("DailyNavs")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrencyRate");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Order", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.ExchangeAccount", "ExchangeAccount")
                        .WithMany("Orders")
                        .HasForeignKey("ExchangeAccountId");

                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "FromCryptoCurrency")
                        .WithMany()
                        .HasForeignKey("FromCryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "ToCryptoCurrency")
                        .WithMany()
                        .HasForeignKey("ToCryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Wallet", "Wallet")
                        .WithMany("Orders")
                        .HasForeignKey("WalletAddress");

                    b.Navigation("ExchangeAccount");

                    b.Navigation("FromCryptoCurrency");

                    b.Navigation("ToCryptoCurrency");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.OrderFunding", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Fund", "Fund")
                        .WithMany("OrderFundings")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Order", "Order")
                        .WithMany("OrderFundings")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Pair", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "FromCryptoCurrency")
                        .WithMany()
                        .HasForeignKey("FromCryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "ToCryptoCurrency")
                        .WithMany()
                        .HasForeignKey("ToCryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromCryptoCurrency");

                    b.Navigation("ToCryptoCurrency");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Trade", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "FeeCurrency")
                        .WithMany()
                        .HasForeignKey("FeeCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Order", "Order")
                        .WithMany("Trades")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeCurrency");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Transfer", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Holding", "Holding")
                        .WithMany("Transfers")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.Transfer", "OppositeTransfer")
                        .WithMany()
                        .HasForeignKey("OppositeTransferId");

                    b.Navigation("Holding");

                    b.Navigation("OppositeTransfer");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Wallet", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.ExchangeAccount", "ExchangeAccount")
                        .WithMany("Wallets")
                        .HasForeignKey("ExchangeAccountId");

                    b.Navigation("ExchangeAccount");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.WalletBalance", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.Wallet", "Wallet")
                        .WithMany("WalletBalances")
                        .HasForeignKey("Address")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.BlockchainNetwork", "BlockchainNetwork")
                        .WithMany("WalletBalances")
                        .HasForeignKey("BlockchainNetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.CryptoCurrency", "CryptoCurrency")
                        .WithMany()
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockchainNetwork");

                    b.Navigation("CryptoCurrency");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodl.Api.HodlDbDomain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Hodl.Api.HodlDbDomain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Bank", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.BankAccount", b =>
                {
                    b.Navigation("Balances");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.BlockchainNetwork", b =>
                {
                    b.Navigation("WalletBalances");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Category", b =>
                {
                    b.Navigation("CryptoCategories");

                    b.Navigation("FundCategories");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.CryptoCurrency", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Currency", b =>
                {
                    b.Navigation("CurrencyRates");

                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Exchange", b =>
                {
                    b.Navigation("ExchangeAccounts");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.ExchangeAccount", b =>
                {
                    b.Navigation("ChildAccounts");

                    b.Navigation("Orders");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Fund", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("DailyNavs");

                    b.Navigation("FundCategories");

                    b.Navigation("Holdings");

                    b.Navigation("Layers");

                    b.Navigation("OrderFundings");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.FundOwner", b =>
                {
                    b.Navigation("Funds");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Holding", b =>
                {
                    b.Navigation("NextHolding");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Order", b =>
                {
                    b.Navigation("OrderFundings");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Hodl.Api.HodlDbDomain.Wallet", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WalletBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
